# Generated by Django 5.1.3 on 2024-11-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True, verbose_name='Post slug'),
            preserve_default=False,
        ),
    ]
